Arrays são um tipo de estrutura que contém apenas números, em sequência.  
Podemos pensar em arrays como sendo vetores ou matrizes.
Arrays são importantes porque trabalhar com eles é muito mais rápido do que trabalhar com listas. Além disso, vários pacotes de Data Science, trabalham com arrays. Não com listas.

Para trabalharmos com arrays, precisamos importar o pacote `numpy`, normalmente abreviado por `np`

In [111]:
import numpy as np

### Definindo um array

In [112]:
#a partir de uma lista
x = np.array([1,2,3,4,5,6,7,8,9, 10, 11, 12])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [113]:
#a partir de um dataframe
import pandas as pd
flores = pd.read_csv('https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv')
flores = flores.select_dtypes(include='float')
flores.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [114]:
flores.to_numpy()

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [115]:
#criando um array com números aleatórios
z = np.random.random(10)
z

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [116]:
#Criando um array com uma sequência de números
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
np.arange(5,10,2)

array([5, 7, 9])

In [118]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### Dimensões de um array

In [119]:
#Relembrar x
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [120]:
#O método shape
x.shape

(12,)

In [121]:
#O método reshape
x = x.reshape(3,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [122]:
x.shape

(3, 4)

In [123]:
#O método reshape com -1
x = x.reshape(2,-1)
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [124]:
x.shape

(2, 6)

### Operações com um array

In [125]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(2,-1)
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [126]:
#Transposição
A.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [127]:
A.T.shape

(6, 2)

In [128]:
#Multiplicação elemento a elemento
A * A

array([[  1,   4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121, 144]])

In [129]:
#Multiplicação matricial
A.T @ A

array([[ 50,  58,  66,  74,  82,  90],
       [ 58,  68,  78,  88,  98, 108],
       [ 66,  78,  90, 102, 114, 126],
       [ 74,  88, 102, 116, 130, 144],
       [ 82,  98, 114, 130, 146, 162],
       [ 90, 108, 126, 144, 162, 180]])

### Operações de Álgebra Linear

O módulo `linalg` dá acesso a funções de álgebra linear:

In [130]:
#Define um vetor para exemplo
# (1, 1)
u = np.ones(2)


#Define uma matriz quadrada para exemplo
# 2    1 #
# 1    2 #
B = np.array([[2,1],[1,2]])

In [131]:
#módulo de um vetor
np.linalg.norm(u)

1.4142135623730951

In [132]:
#determinante
np.linalg.det(B)

2.9999999999999996

In [133]:
#rank
np.linalg.matrix_rank(B)

2

In [134]:
#inverso
C = np.linalg.inv(B)
C

array([[ 0.66666667, -0.33333333],
       [-0.33333333,  0.66666667]])

In [135]:
B @ C

array([[1., 0.],
       [0., 1.]])

In [136]:
#Autovalores e autovetores
np.linalg.eig(B)

(array([3., 1.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [137]:
#Decomposição QR
np.linalg.qr(B)

(array([[-0.89442719, -0.4472136 ],
        [-0.4472136 ,  0.89442719]]),
 array([[-2.23606798, -1.78885438],
        [ 0.        ,  1.34164079]]))

In [138]:
#Decomposição em valores singulares
np.linalg.svd(B)

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([3., 1.]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

### Operações ao longo dos eixos de um array

In [139]:
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

#### Soma

Podemos obter a soma das colunas de um array:

In [140]:
A.sum(axis = 0)

array([ 8, 10, 12, 14, 16, 18])

Podemos obter a soma das linhas de um array:

In [141]:
A.sum(axis = 1)

array([21, 57])

Podemos simplesmente somar todos os números de um array:

In [142]:
A.sum()

78

#### Média

A mesma coisa vale para média:

In [143]:
A.mean(axis = 0)

array([4., 5., 6., 7., 8., 9.])

In [144]:
A.mean(axis = 1)

array([3.5, 9.5])

In [145]:
A.mean()

6.5

Várias funções seguem a mesma lógica que soma e média:
* `max`, `min`
* `std`, `var`  
e mais!

### Produto escalar

$$
\vec{u} \cdot \vec{v} = \sum_{i=1}^{n} u_iv_i
$$

In [158]:
u = np.array([1,2,3]) #preços
v = np.array([3,2,1]) #quantidades

In [159]:
u.dot(v) #valor total

10

### Vetorização

Operações se tornam muito mais rápidas se escritas na forma de uma operação entre vetores e matrizes.

#### Exemplo 1 : Calcular o dobro de todos os números de 0 a 10 milhões

In [69]:
N = 10**7
u = np.arange(N)

In [70]:
%%timeit
v = np.empty(N)
for i in range(N):
    v[i] = 2 * u[i]

9.62 s ± 724 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [71]:
%%timeit
v = 2 * u

26 ms ± 1.14 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### Exemplo 2: Produto escalar de dois vetores com 10 milhões de elementos

In [72]:
N = 10**7
u = np.repeat(1, N)
v = np.repeat(1, N)

In [73]:
%%timeit
s = 0
for i in range(N):
    s += v[i] * u[i]

7.26 s ± 214 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [74]:
%%timeit
u.dot(v)

17.1 ms ± 1.63 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


> __Sempre que possível, trabalhe com vetores e matrizes.   
> É muito mais rápido do que trabalhar com os elementos desses vetores ou matrizes individualmente.  
> Chamamos isso de *vetorizaçãoo*__


### Filtrando um array

Arrays se filtram que nem DataFrames usando o método `.iloc`:

In [75]:
z = np.random.random(25).reshape(5,5)
z

array([[0.6572784 , 0.61312031, 0.72310522, 0.18203916, 0.77523558],
       [0.36534532, 0.15097176, 0.45968355, 0.84882556, 0.52533121],
       [0.35808121, 0.40910142, 0.06324676, 0.74977578, 0.70998574],
       [0.9255408 , 0.35983058, 0.78447261, 0.07626521, 0.74801214],
       [0.12365928, 0.58380931, 0.86152775, 0.10540725, 0.43161477]])

In [76]:
#Um índice filtra a linha
z[0]

array([0.6572784 , 0.61312031, 0.72310522, 0.18203916, 0.77523558])

In [77]:
#Dois filtram linha e coluna
z[0, 2]

0.7231052223954638

In [78]:
#O ":" representa um intervalo que inclui o primeiro elemento mas não inclui o segundo
z[0:2, 3:]

array([[0.18203916, 0.77523558],
       [0.84882556, 0.52533121]])

In [79]:
#np.where
x = np.array([10,20,30,40,50,40,30,20,10])
np.where(x == x.max())

(array([4], dtype=int64),)

In [80]:
np.where(x == x.max())[0]

array([4], dtype=int64)

### Arrays aleatórios

O módulo `numpy.random` permite gerar arrays com números aleatórios.  
A função `random` gera um array com números aleatórios entre 0 e 1.

In [81]:
import numpy.random as npr

In [82]:
npr.random(10)

array([0.05446433, 0.80604131, 0.74338701, 0.45422321, 0.85205164,
       0.78443716, 0.52063744, 0.72200366, 0.11048329, 0.86804311])

Se quisermos números aleatórios em outro intervalo, podemos usar a função `uniform`:

In [83]:
npr.uniform(low = 50, high=100, size = 3)

array([65.5495134 , 69.0124398 , 53.38418359])

Se quisermos reproduzir sempre os mesmos resultados, podemos definir uma semente de números aleatórios:

In [84]:
npr.seed(0)
npr.random(10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [85]:
npr.seed(0)
npr.random(10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

Existem várias outras funções para a geração de números aleatórios. Você vai aprender mais sobre isso em Estatística. 

### Numpy não é só arrays...

In [86]:
np.inf

inf

In [87]:
np.nan

nan

A função `isclose` também é útil para lidar com problemas que surgem por arredondamentos devido à forma como computadores processam números reais. Observe:

In [88]:
0.1 + 0.1 + 0.1 == 0.3

False

In [89]:
np.isclose(0.1 + 0.1 + 0.1, 0.3)

True

Discutir o porquê que coisas assim acontecem está além do escopo do nosso curso. Mas vale a pena saber que a função `isclose` existe e pode ser útil em casos como esses.